### ISSUE TITLE
rampart with dorado's .fastq

### ISSUE THREAD

**Issue by doloacu** [artic-network/rampart#117]
Hello, for first time I am having some problems since I started to use rampart after generate my fastq with dorado. I have this kind of problems:
(artic-rampart) minion@minion-H470M-DS3H:~/Documents/20240916/rampart-rsv$ rampart --protocol . --basecalledPath /home/minion/Documents/20240916/demux-dorado-fast
Creating path /home/minion/Documents/20240916/rampart-rsv/annotations/

---------------------------------------------------------------------------
RAMPART daemon running
socket open on port 3001 for all data communication
---------------------------------------------------------------------------

---------------------------------------------------------------------------
Serving built bundle at http://localhost:3000
---------------------------------------------------------------------------

Found 0 annotated CSV files in .../rampart-rsv/annotations/. FASTQs with the same filename as these will be ignored.
Scanning folder /home/minion/Documents/20240916/demux-dorado-fast/ for FASTQs
(basecalled files which exist here (or are created here by MinKNOW) will be annotated and loaded)

Initial scan for FASTQs complete. Found 88 files, 88 of which are unannotated (unprocesed).
Watching for new files
[warning]  pipeline (Annotate reads) finished with exit code 1. Error messages:
[warning]  	Building DAG of jobs...

[warning]  	Relative file path './references.fasta' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.

[warning]  	Relative file path './references.fasta' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.

[warning]  	Using shell: /usr/bin/bash
Provided cores: 2

[warning]  	Rules claiming more threads will be scaled down.

[warning]  	Job counts:
	count	jobs
	1	all
	1	minimap2
	1	parse_mapping
	3

[warning]  	
[Wed Sep 18 13:39:03 2024]

[warning]  	rule minimap2:
    input: /home/minion/Documents/20240916/demux-dorado-fast/SQK-RBK110-96_barcode01.fastq, ./references.fasta
    output: /home/minion/Documents/20240916/rampart-rsv/annotations/temp/SQK-RBK110-96_barcode01.paf
    jobid: 2
    wildcards: filename_stem=SQK-RBK110-96_barcode01
    threads: 2

[warning]  	

[warning]  	[M::mm_idx_gen::0.001*1.45] collected minimizers

[warning]  	[M::mm_idx_gen::0.002*1.67] sorted minimizers
[M::main::0.002*1.66] loaded/built the index for 1 target sequence(s)

[warning]  	[M::mm_mapopt_update::0.002*1.61] mid_occ = 3
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1

[warning]  	[M::mm_idx_stat::0.002*1.57] distinct minimizers: 5543 (97.44% are singletons); average occurrences: 1.026; average spacing: 5.419

[warning]  	[M::worker_pipeline::3.230*1.92] mapped 76470 sequences

[warning]  	[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -t 2 -x map-ont --secondary=no --paf-no-hit --cs ./references.fasta /home/minion/Documents/20240916/demux-dorado-fast/SQK-RBK110-96_barcode01.fastq
[M::main] Real time: 3.230 sec; CPU: 6.188 sec; Peak RSS: 0.091 GB

[warning]  	[Wed Sep 18 13:39:06 2024]

[warning]  	Finished job 2.

[warning]  	1 of 3 steps (33%) done

[warning]  	
[Wed Sep 18 13:39:06 2024]

[warning]  	rule parse_mapping:
    input: /home/minion/Documents/20240916/demux-dorado-fast/SQK-RBK110-96_barcode01.fastq, /home/minion/Documents/20240916/rampart-rsv/annotations/temp/SQK-RBK110-96_barcode01.paf, ./references.fasta
    output: /home/minion/Documents/20240916/rampart-rsv/annotations/SQK-RBK110-96_barcode01.csv
    jobid: 1
    wildcards: filename_stem=SQK-RBK110-96_barcode01

[warning]  	

[warning]  	Traceback (most recent call last):
  File "/home/minion/rampart/default_protocol/pipelines/demux_map/rules/parse_paf.py", line 83, in get_header_dict
    barcode = header["barcode"]
KeyError: 'barcode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minion/rampart/default_protocol/pipelines/demux_map/rules/parse_paf.py", line 288, in <module>
    header_dict = get_header_dict(args.reads)
  File "/home/minion/rampart/default_protocol/pipelines/demux_map/rules/parse_paf.py", line 87, in get_header_dict
    start_time = header["start_time"]
KeyError: 'start_time'

[warning]  	[Wed Sep 18 13:39:06 2024]

[warning]  	Error in rule parse_mapping:
    jobid: 1

[warning]  	    output: /home/minion/Documents/20240916/rampart-rsv/annotations/SQK-RBK110-96_barcode01.csv

[warning]  	    shell:
        
        python /home/minion/rampart/default_protocol/pipelines/demux_map/rules/parse_paf.py         --paf_file /home/minion/Documents/20240916/rampart-rsv/annotations/temp/SQK-RBK110-96_barcode01.paf         --report /home/minion/Documents/20240916/rampart-rsv/annotations/SQK-RBK110-96_barcode01.csv         --annotated_reads /home/minion/Documents/20240916/demux-dorado-fast/SQK-RBK110-96_barcode01.fastq         --reference_file ./references.fasta                  --reference_options ""
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by rmcolq** [comment]
Does Dorado still include the `start_time` in the header of reads?
