### ISSUE TITLE
System limit for number of file watchers reached when using millions of reads

### ISSUE THREAD

**Issue by jagos01** [artic-network/rampart#90]
when running rampart with a large number of reads (~2 milion) I get the following error:

(node:13233) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/data1/Raw_Data/ncov2_seq/Z444_Zymo/ghac_4.5.4-2/pass/fastq_runid_0792bc9fc34b63218e65ffa397ba92c0fa945c17_2299_1.fastq'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1444:11)
    at createFsWatchInstance (/mnt/data0/miniconda3/envs/artic/lib/node_modules/artic-rampart/node_modules/chokidar/lib/nodefs-handler.js:118:15)
    at setFsWatchListener (/mnt/data0/miniconda3/envs/artic/lib/node_modules/artic-rampart/node_modules/chokidar/lib/nodefs-handler.js:165:15)
    at NodeFsHandler._watchWithNodeFs (/mnt/data0/miniconda3/envs/artic/lib/node_modules/artic-rampart/node_modules/chokidar/lib/nodefs-handler.js:330:14)
    at NodeFsHandler._handleFile (/mnt/data0/miniconda3/envs/artic/lib/node_modules/artic-rampart/node_modules/chokidar/lib/nodefs-handler.js:360:23)
    at NodeFsHandler._addToNodeFs (/mnt/data0/miniconda3/envs/artic/lib/node_modules/artic-rampart/node_modules/chokidar/lib/nodefs-handler.js:620:21)
(node:13233) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2178)

Do you have any suggestions on how to resolve this issue?
Thanks,
Scott

**Comment by BenjaminSchwessinger** [comment]
Hi there. We are getting a similar error with about 1.75 Million reads. Any pointers welcome.
